name: Lint Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Needs to manually be updated

    - name: Install dependencies
      run: |
         rm -rf node_modules package-lock.json
         npm install --ignore-scripts
         npm install @rollup/rollup-linux-x64-gnu
         npx nuxt prepare

    - name: Run ESLint
      run: |
        npm run lint
